# Generated by Django 5.1.7 on 2025-03-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='password_last_changed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
