# Generated by Django 5.1.7 on 2025-03-27 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_patient_patientlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientlink',
            name='account',
        ),
    ]
