# Generated by Django 5.1.7 on 2025-03-27 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_patientlink_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientlink',
            name='account',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='account', to='main.userprofiles'),
            preserve_default=False,
        ),
    ]
